# Generated by Django 5.0.3 on 2024-08-03 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_created_at_alter_listing_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 0, 34, 55, 723690, tzinfo=datetime.timezone.utc)),
        ),
    ]
